Bug #50648 UDM syntax: cmp is deprecated
giving cmp and key then cmp will be ignored. cmp=localte.strcoll never worked (and has a different function signature)

Traceback (most recent call last):
  File "/usr/share/univention-directory-manager-tools/univention-cli-server", line 48, in <module>
    import univention.admincli.adduser
  File "/usr/lib/python3/dist-packages/univention/admincli/adduser.py", line 41, in <module>
    import univention.admin.uldap
  File "/usr/lib/python3/dist-packages/univention/admin/__init__.py", line 632, in <module>
    from univention.admin import modules, objects, syntax, hook, mapping  # noqa
  File "/usr/lib/python3/dist-packages/univention/admin/modules.py", line 47, in <module>
    import univention.admin.syntax
  File "/usr/lib/python3/dist-packages/univention/admin/syntax.py", line 5187, in <module>
    Country.update_choices()
  File "/usr/lib/python3/dist-packages/univention/admin/syntax.py", line 5158, in update_choices
    cls.choices.sort(cmp=locale.strcoll, key=itemgetter(1))
TypeError: 'cmp' is an invalid keyword argument for this function